import CitySubpageHeader from '@/components/CitySubpageHeader'
import Footer from '@/components/Footer'
import CityTabbedList from '@/components/CityTabbedList'

const tabs = [
  { value: 'all', label: '全部', dataArea: 'all' },
  { value: '沙壩', label: '沙壩', dataArea: '沙壩' },
  { value: '下龍灣', label: '下龍灣', dataArea: '下龍灣' },
  { value: '陸龍灣', label: '陸龍灣', dataArea: '陸龍灣' },
  { value: '河內', label: '河內', dataArea: '河內' },
]

const cards = [
  { title: '番西邦峰', meta: '沙壩', area: '沙壩', datasetKey: 'title' as const, datasetValue: '番西邦峰', actions: [{ label: 'KKDAY', href: 'https://www.kkday.com/zh-tw/product/36100-sapa-sunworld-fansipan-legend-cable-car-ticket?cid=22312', className: 'btn primary', event: 'northvietnamticket_fansipanKKday', platform: 'KKDAY', section: 'ticket_card' }, { label: 'KLOOK', href: 'https://www.klook.com/zh-TW/activity/11904-fansipan-cable-car-ticket-transfers-sapa/?aid=93798', className: 'btn', event: 'northvietnamticket_fansipanKLOOK', platform: 'KLOOK', section: 'ticket_card' }, { label: 'Trip', href: 'https://tw.trip.com/travel-guide/attraction/tt-sa-pa/sun-world-fansipan-legend-130369464?Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D5784662', className: 'btn', event: 'northvietnamticket_fansipanTrip', platform: 'Trip', section: 'ticket_card' }] },
  { title: '玻璃天空步道', meta: '沙壩', area: '沙壩', datasetKey: 'title' as const, datasetValue: '玻璃天空步道', actions: [{ label: 'KKDAY', href: 'https://www.kkday.com/zh-tw/product/139366-rong-may-sapa-glass-bridge-ticket-vietnam?cid=22312', className: 'btn primary', event: 'northvietnamticket_bridgeKKday', platform: 'KKDAY', section: 'ticket_card' }, { label: 'KLOOK', href: 'https://www.klook.com/zh-TW/activity/57672-rong-may-sapa-glass-bridge-ticket/?aid=93798', className: 'btn', event: 'northvietnamticket_bridgeKLOOK', platform: 'KLOOK', section: 'ticket_card' }, { label: 'Trip', href: 'https://tw.trip.com/things-to-do/detail/97861270?Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D5784662', className: 'btn', event: 'northvietnamticket_bridgeTrip', platform: 'Trip', section: 'ticket_card' }] },
  { title: '頂級郵輪｜2天1夜', meta: '下龍灣', area: '下龍灣', datasetKey: 'title' as const, datasetValue: '頂級郵輪｜2天1夜', actions: [{ label: 'KKDAY', href: 'https://www.kkday.com/zh-tw/product/284294?cid=22312', className: 'btn primary', event: 'northvietnamticket_highcruiseKKday', platform: 'KKDAY', section: 'ticket_card' }] },
  { title: 'Athena Cruise｜2天1夜', meta: '下龍灣', area: '下龍灣', datasetKey: 'title' as const, datasetValue: 'Athena Cruise｜2天1夜', actions: [{ label: 'KKDAY', href: 'https://www.kkday.com/zh-tw/product/183280?cid=22312', className: 'btn primary', event: 'northvietnamticket_AthenacruiseKKday', platform: 'KKDAY', section: 'ticket_card' }, { label: 'KLOOK', href: 'https://www.klook.com/zh-TW/activity/45689-ha-long-bay-athena-luxury-cruise/?aid=93798', className: 'btn', event: 'northvietnamticket_AthenacruiseKLOOK', platform: 'KLOOK', section: 'ticket_card' }] },
  { title: 'Aqua Elegance｜2天1夜', meta: '下龍灣', area: '下龍灣', datasetKey: 'title' as const, datasetValue: 'Aqua Elegance｜2天1夜', actions: [{ label: 'KKDAY', href: 'https://www.kkday.com/zh-tw/product/530569?cid=22312', className: 'btn primary', event: 'northvietnamticket_AquacruiseKKday', platform: 'KKDAY', section: 'ticket_card' }, { label: 'KLOOK', href: 'https://www.klook.com/zh-TW/activity/131806-ha-long-bay-aqua-elegance-luxury-cruise/?aid=93798', className: 'btn', event: 'northvietnamticket_AquacruiseKLOOK', platform: 'KLOOK', section: 'ticket_card' }] },
  { title: 'Alisa Premier Cruise｜2天1夜', meta: '下龍灣', area: '下龍灣', datasetKey: 'title' as const, datasetValue: 'Alisa Premier Cruise｜2天1夜', actions: [{ label: 'KLOOK', href: 'https://www.klook.com/zh-TW/activity/98369-ha-long-bay-alisa-premier-luxury-cruise/?aid=93798', className: 'btn primary', event: 'northvietnamticket_AlisacruiseKLOOK', platform: 'KLOOK', section: 'ticket_card' }] },
  { title: 'Ambassador Cruise｜1日遊', meta: '下龍灣', area: '下龍灣', datasetKey: 'title' as const, datasetValue: 'Ambassador Cruise｜1日遊', actions: [{ label: 'KKDAY', href: 'https://www.kkday.com/zh-tw/product/266831?cid=22312', className: 'btn primary', event: 'northvietnamticket_AmbassadorcruiseKKday', platform: 'KKDAY', section: 'ticket_card' }, { label: 'KLOOK', href: 'https://www.klook.com/zh-TW/activity/36086-halong-bay-cruise-tour-hanoi/?aid=93798', className: 'btn', event: 'northvietnamticket_AmbassadorcruiseKLOOK', platform: 'KLOOK', section: 'ticket_card' }] },
  { title: 'Olympus Day Cruise｜1日遊', meta: '下龍灣', area: '下龍灣', datasetKey: 'title' as const, datasetValue: 'Olympus Day Cruise｜1日遊', actions: [{ label: 'KLOOK', href: 'https://www.klook.com/zh-TW/activity/133081-ha-long-bay-day-tour-olympus-luxury-cruise/?aid=93798', className: 'btn primary', event: 'northvietnamticket_OlympuscruiseKLOOK', platform: 'KLOOK', section: 'ticket_card' }] },
  { title: '方案1｜華閭 - 三谷/長安 - 舞洞', meta: '陸龍灣', area: '陸龍灣', datasetKey: 'title' as const, datasetValue: '方案1｜華閭 - 三谷/長安 - 舞洞', actions: [{ label: 'KLOOK', href: 'https://www.klook.com/zh-TW/activity/29360-hoa-lu-tam-coc-mua-cave-tour-hanoi-vietnamese-dinner/?aid=93798', className: 'btn primary', event: 'northvietnamticket_TrangAn1KLOOK', platform: 'KLOOK', section: 'ticket_card' }] },
  { title: '方案2｜白亭 - 長安 - 舞洞', meta: '陸龍灣', area: '陸龍灣', datasetKey: 'title' as const, datasetValue: '方案2｜白亭 - 長安 - 舞洞', actions: [{ label: 'KLOOK', href: 'https://www.klook.com/zh-TW/activity/145586-ninhbinh-day-tour-hanoi/?aid=93798', className: 'btn primary', event: 'northvietnamticket_TrangAn2KLOOK', platform: 'KLOOK', section: 'ticket_card' }] },
  { title: '方案3｜華閭 - 白亭 - 長安 - 舞洞', meta: '陸龍灣', area: '陸龍灣', datasetKey: 'title' as const, datasetValue: '方案3｜華閭 - 白亭 - 長安 - 舞洞', actions: [{ label: 'KLOOK', href: 'https://www.klook.com/zh-TW/activity/19260-hoa-lu-tam-coc-hanoi-halong-bay/?aid=93798', className: 'btn primary', event: 'northvietnamticket_TrangAn3KLOOK', platform: 'KLOOK', section: 'ticket_card' }] },
  { title: '方案4｜華閭 - 三谷 - 舞洞 - 白亭 - 長安', meta: '陸龍灣', area: '陸龍灣', datasetKey: 'title' as const, datasetValue: '方案4｜華閭 - 三谷 - 舞洞 - 白亭 - 長安', actions: [{ label: 'KLOOK', href: 'https://www.klook.com/zh-TW/activity/146528-2d1n-hoa-lu-tam-coc-hang-mua-bai-dinh-trang-an-tour-from-hanoi/?aid=93798', className: 'btn primary', event: 'northvietnamticket_TrangAn4KLOOK', platform: 'KLOOK', section: 'ticket_card' }] },
  { title: 'La Belle Spa按摩', meta: '河內', area: '河內', datasetKey: 'title' as const, datasetValue: 'La Belle Spa按摩', actions: [{ label: 'KKDAY', href: 'https://www.kkday.com/zh-tw/product/32025-ha-noi-la-belle-spa-message-voucher/?cid=22312', className: 'btn primary', event: 'northvietnamticket_HanoiLabelleKKday', platform: 'KKDAY', section: 'ticket_card' }, { label: 'KLOOK', href: 'https://www.klook.com/zh-TW/activity/18679-la-belle-spa-hanoi-halong-bay/?aid=93798', className: 'btn', event: 'northvietnamticket_HanoiLabelleKLOOK', platform: 'KLOOK', section: 'ticket_card' }] },
  { title: '河內市區半日遊', meta: '河內', area: '河內', datasetKey: 'title' as const, datasetValue: '河內市區半日遊', actions: [{ label: 'KKDAY', href: 'https://www.kkday.com/zh-tw/product/531327?cid=22312', className: 'btn primary', event: 'northvietnamticket_HanoihalfKKday', platform: 'KKDAY', section: 'ticket_card' }, { label: 'KLOOK', href: 'https://www.klook.com/zh-TW/activity/30643-hanoi-half-day-city-tour/?aid=93798', className: 'btn', event: 'northvietnamticket_HanoihalfKLOOK', platform: 'KLOOK', section: 'ticket_card' }] },
  { title: '老城區美食之旅', meta: '河內', area: '河內', datasetKey: 'title' as const, datasetValue: '老城區美食之旅', actions: [{ label: 'KKDAY', href: 'https://www.kkday.com/zh-tw/product/131886?cid=22312', className: 'btn primary', event: 'northvietnamticket_HanoifoodKKday', platform: 'KKDAY', section: 'ticket_card' }, { label: 'KLOOK', href: 'https://www.klook.com/zh-TW/activity/1969-old-quarter-food-tour-hanoi/?aid=93798', className: 'btn', event: 'northvietnamticket_HanoifoodKLOOK', platform: 'KLOOK', section: 'ticket_card' }] },
  { title: '吉普車觀光半日遊', meta: '河內', area: '河內', datasetKey: 'title' as const, datasetValue: '吉普車觀光半日遊', actions: [{ label: 'KKDAY', href: 'https://www.kkday.com/zh-tw/product/286204?cid=22312', className: 'btn primary', event: 'northvietnamticket_HanoiJeepKKday', platform: 'KKDAY', section: 'ticket_card' }, { label: 'KLOOK', href: 'https://www.klook.com/zh-TW/activity/31346-hanoi-vintage-army-jeep-tour/?aid=93798', className: 'btn', event: 'northvietnamticket_HanoiJeepKLOOK', platform: 'KLOOK', section: 'ticket_card' }] },
  { title: '雙層觀光巴士', meta: '河內', area: '河內', datasetKey: 'title' as const, datasetValue: '雙層觀光巴士', actions: [{ label: 'KKDAY', href: 'https://www.kkday.com/zh-tw/product/28299-hanoi-hop-on-hop-off-bus-ticket-vietnam?cid=22312', className: 'btn primary', event: 'northvietnamticket_HanoiBusKKday', platform: 'KKDAY', section: 'ticket_card' }, { label: 'KLOOK', href: 'https://www.klook.com/zh-TW/activity/87164-hanoi-hop-on-off-sightseeing-tour/?aid=93798', className: 'btn', event: 'northvietnamticket_HanoiBusKLOOK', platform: 'KLOOK', section: 'ticket_card' }] },
  { title: '水上木偶秀', meta: '河內', area: '河內', datasetKey: 'title' as const, datasetValue: '水上木偶秀', actions: [{ label: 'KKDAY', href: 'https://www.kkday.com/zh-tw/product/129554-hanoi-water-puppet-show-express-pass-vietnam?cid=22312', className: 'btn primary', event: 'northvietnamticket_WaterArtKKday', platform: 'KKDAY', section: 'ticket_card' }, { label: 'KLOOK', href: 'https://www.klook.com/zh-TW/activity/35653-thang-long-water-puppet-show-ticket-hanoi/?aid=93798', className: 'btn', event: 'northvietnamticket_WaterArtKLOOK', platform: 'KLOOK', section: 'ticket_card' }] },
  { title: '樂天觀景台', meta: '河內', area: '河內', datasetKey: 'title' as const, datasetValue: '樂天觀景台', actions: [{ label: 'KKDAY', href: 'https://www.kkday.com/zh-tw/product/23559-ha-noi-lotte-observation-deck-transparent-skywalk-ticket?cid=22312', className: 'btn primary', event: 'northvietnamticket_ObsDeckKKday', platform: 'KKDAY', section: 'ticket_card' }, { label: 'KLOOK', href: 'https://www.klook.com/zh-TW/activity/22529-lotte-observation-deck-ticket-hanoi/?aid=93798', className: 'btn', event: 'northvietnamticket_ObsDeckKLOOK', platform: 'KLOOK', section: 'ticket_card' }] },
  { title: '樂天世界水族館', meta: '河內', area: '河內', datasetKey: 'title' as const, datasetValue: '樂天世界水族館', actions: [{ label: 'KKDAY', href: 'https://www.kkday.com/zh-tw/product/163666-vinvonders-hanoi-congviennuoc?cid=22312', className: 'btn primary', event: 'northvietnamticket_SeaKKday', platform: 'KKDAY', section: 'ticket_card' }, { label: 'KLOOK', href: 'https://www.klook.com/zh-TW/activity/109708-ha-noi-lotte-world-aquarium/?aid=93798', className: 'btn', event: 'northvietnamticket_SeaKLOOK', platform: 'KLOOK', section: 'ticket_card' }] },
]

export default function NorthVietnamTicketPage() {
  return (
    <>
      <CitySubpageHeader backHref="/northvietnam" eventPrefix="northvietnamticket" />
      <main className="busan-main transport-main">
        <h1>越南北越｜票券購買</h1>
        <CityTabbedList tabs={tabs} cards={cards} tabEvent="northvietnam_ticket_tab" />
      </main>
      <Footer />
    </>
  )
}
