import type { MetadataRoute } from 'next'

const SITE_URL = 'https://www.jiejourneys.com'

type ChangeFrequency = NonNullable<MetadataRoute.Sitemap[number]['changeFrequency']>

type SitemapRoute = {
  path: string
  changeFrequency?: ChangeFrequency
  priority?: number
  images?: string[]
}

const lastModifiedByPath: Record<string, string> = {
  '/': '2026-07-11',
  '/contact': '2026-04-10',
  '/countries': '2026-05-09',
  '/tools/planner': '2026-07-13',
  '/tools/bill': '2026-04-16',
  '/tools/resources': '2026-07-01',
  '/japan/tax-free-2026': '2026-07-14',
  '/japan/visit-japan-web-guide': '2026-07-22',
  '/busan': '2026-05-17',
  '/busan/hotel': '2026-06-06',
  '/busan/ticket': '2026-06-15',
  '/busan/transport': '2026-05-17',
  '/busan/video': '2026-05-09',
  '/busan/map': '2026-06-18',
  '/busan/pass-map': '2026-06-17',
  '/busan/visit-busan-pass': '2026-07-16',
  '/busan/busan-yacht-suyeong-diamond-bay': '2026-07-16',
  '/busan/busan-fast-guide': '2026-07-18',
  '/busan/nampo-dong-guide': '2026-07-18',
  '/busan/gamcheon-culture-village-guide': '2026-07-18',
  '/busan/busan-tower-guide': '2026-07-18',
  '/busan/haeundae-guide': '2026-07-18',
  '/busan/capsule-train-guide': '2026-07-18',
  '/busan/visit-busan-pass-24h-route': '2026-07-18',
  '/busan/visit-busan-pass-48h-route': '2026-07-18',
  '/busan/busan-preparation-guide': '2026-07-22',
  '/busan/korea-e-arrival-card-guide': '2026-07-22',
  '/busan/k-eta-guide': '2026-07-22',
  '/busan/journeys': '2026-05-01',
  '/northvietnam': '2026-05-12',
  '/northvietnam/hotel': '2026-06-06',
  '/northvietnam/ticket': '2026-06-15',
  '/northvietnam/transport': '2026-05-17',
  '/northvietnam/hanoi-to-sapa-transport': '2026-07-16',
  '/northvietnam/video': '2026-05-10',
  '/northvietnam/map': '2026-06-18',
  '/northvietnam/journeys': '2026-04-25',
  '/tokyo': '2026-05-01',
  '/tokyo/hotel': '2026-06-06',
  '/tokyo/ticket': '2026-06-15',
  '/tokyo/transport': '2026-07-01',
  '/tokyo/narita-airport-to-tokyo': '2026-07-16',
  '/tokyo/haneda-airport-to-tokyo': '2026-07-16',
  '/tokyo/tokyo-subway-ticket': '2026-07-16',
  '/tokyo/tokyo-subway-vs-jr-guide': '2026-07-22',
  '/tokyo/jr-vs-shinkansen-guide': '2026-07-22',
  '/tokyo/tokyo-9-areas-guide': '2026-07-18',
  '/tokyo/sensoji-guide': '2026-07-18',
  '/tokyo/skytree-guide': '2026-07-18',
  '/tokyo/meiji-jingu-guide': '2026-07-18',
  '/tokyo/shibuya-sky-guide': '2026-07-18',
  '/tokyo/video': '2026-07-14',
  '/tokyo/map': '2026-06-18',
  '/tokyo/journeys': '2026-04-25',
  '/osaka': '2026-07-11',
  '/osaka/hotel': '2026-06-18',
  '/osaka/ticket': '2026-07-11',
  '/osaka/transport': '2026-07-01',
  '/osaka/kansai-airport-to-osaka': '2026-07-16',
  '/osaka/kansai-airport-terminal-guide': '2026-08-11',
  '/osaka/osaka-castle-guide': '2026-07-22',
  '/osaka/tsutenkaku-guide': '2026-07-28',
  '/osaka/dotonbori-cruise-guide': '2026-08-04',
  '/osaka/osaka-5-areas-guide': '2026-07-22',
  '/osaka/video': '2026-07-14',
  '/osaka/map': '2026-06-18',
  '/osaka/pass-map': '2026-07-11',
  '/osaka/osaka-amazing-pass': '2026-07-11',
  '/osaka/journeys': '2026-04-10',
  '/fuji': '2026-05-27',
  '/fuji/hotel': '2026-06-06',
  '/fuji/ticket': '2026-06-15',
  '/fuji/transport': '2026-07-01',
  '/fuji/tokyo-to-kawaguchiko': '2026-07-16',
  '/fuji/mt-fuji-pass': '2026-07-16',
  '/fuji/video': '2026-05-17',
  '/fuji/map': '2026-06-18',
  '/fuji/pass-map': '2026-06-17',
}

const sitemapRoutes: SitemapRoute[] = [
  { path: '/', changeFrequency: 'weekly', priority: 1 },
  { path: '/contact', changeFrequency: 'yearly', priority: 0.3 },
  { path: '/countries', changeFrequency: 'monthly', priority: 0.5 },
  { path: '/tools/planner', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/tools/bill', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/tools/resources', changeFrequency: 'monthly', priority: 0.5 },

  { path: '/japan/tax-free-2026', changeFrequency: 'monthly', priority: 0.8, images: ['/assets/japan-tax-free-comparison-2026.png'] },
  { path: '/japan/visit-japan-web-guide', changeFrequency: 'monthly', priority: 0.8 },

  { path: '/busan', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/busan/hotel', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/busan/ticket', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/busan/transport', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/busan/video', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/busan/map', changeFrequency: 'monthly', priority: 0.8, images: ['/assets/busan-map-search.png'] },
  { path: '/busan/pass-map', changeFrequency: 'monthly', priority: 0.8, images: ['/assets/busan-passmap-search.png'] },
  { path: '/busan/visit-busan-pass', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/busan/busan-yacht-suyeong-diamond-bay', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/busan/busan-fast-guide', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/busan/nampo-dong-guide', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/busan/gamcheon-culture-village-guide', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/busan/busan-tower-guide', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/busan/haeundae-guide', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/busan/capsule-train-guide', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/busan/visit-busan-pass-24h-route', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/busan/visit-busan-pass-48h-route', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/busan/busan-preparation-guide', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/busan/korea-e-arrival-card-guide', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/busan/k-eta-guide', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/busan/journeys', changeFrequency: 'monthly', priority: 0.6 },

  { path: '/northvietnam', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/northvietnam/hotel', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/northvietnam/ticket', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/northvietnam/transport', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/northvietnam/hanoi-to-sapa-transport', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/northvietnam/video', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/northvietnam/map', changeFrequency: 'monthly', priority: 0.8, images: ['/assets/northvietnam-map-search.png'] },
  { path: '/northvietnam/journeys', changeFrequency: 'monthly', priority: 0.6 },

  { path: '/tokyo', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/tokyo/hotel', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/tokyo/ticket', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/tokyo/transport', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/tokyo/narita-airport-to-tokyo', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/tokyo/haneda-airport-to-tokyo', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/tokyo/tokyo-subway-ticket', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/tokyo/tokyo-subway-vs-jr-guide', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/tokyo/jr-vs-shinkansen-guide', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/tokyo/tokyo-9-areas-guide', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/tokyo/sensoji-guide', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/tokyo/skytree-guide', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/tokyo/meiji-jingu-guide', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/tokyo/shibuya-sky-guide', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/tokyo/video', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/tokyo/map', changeFrequency: 'monthly', priority: 0.8, images: ['/assets/tokyo-map-search.png'] },
  { path: '/tokyo/journeys', changeFrequency: 'monthly', priority: 0.6 },

  { path: '/osaka', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/osaka/hotel', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/osaka/ticket', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/osaka/transport', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/osaka/kansai-airport-to-osaka', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/osaka/kansai-airport-terminal-guide', changeFrequency: 'monthly', priority: 0.8, images: ['/assets/kansai-airport-terminal/terminal-1-floor-guide.jpg', '/assets/kansai-airport-terminal/terminal-2-guide.jpg'] },
  { path: '/osaka/osaka-castle-guide', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/osaka/tsutenkaku-guide', changeFrequency: 'monthly', priority: 0.8, images: ['/assets/tsutenkaku/facilities-floors.png', '/assets/tsutenkaku/shopping-streets-map.png'] },
  { path: '/osaka/dotonbori-cruise-guide', changeFrequency: 'monthly', priority: 0.8, images: ['/assets/dotonbori-cruise/wonder-glico-night.png', '/assets/dotonbori-cruise/cruise-comparison.png'] },
  { path: '/osaka/osaka-5-areas-guide', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/osaka/video', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/osaka/map', changeFrequency: 'monthly', priority: 0.8, images: ['/assets/osaka-map-search.png'] },
  { path: '/osaka/pass-map', changeFrequency: 'monthly', priority: 0.8, images: ['/assets/osaka-passmap-search.png'] },
  { path: '/osaka/osaka-amazing-pass', changeFrequency: 'monthly', priority: 0.8, images: ['/assets/osaka-pass-summary.png', '/assets/osaka-pass-free-attractions.png'] },
  { path: '/osaka/journeys', changeFrequency: 'monthly', priority: 0.6 },

  { path: '/fuji', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/fuji/hotel', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/fuji/ticket', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/fuji/transport', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/fuji/tokyo-to-kawaguchiko', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/fuji/mt-fuji-pass', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/fuji/video', changeFrequency: 'monthly', priority: 0.7 },
  { path: '/fuji/map', changeFrequency: 'monthly', priority: 0.8, images: ['/assets/fuji-map-search.png'] },
  { path: '/fuji/pass-map', changeFrequency: 'monthly', priority: 0.8, images: ['/assets/fuji-passmap-search.png'] },
]

export default function sitemap(): MetadataRoute.Sitemap {
  return sitemapRoutes.map(({ path, images, ...route }) => {
    const lastModified = lastModifiedByPath[path]

    return {
      url: `${SITE_URL}${path}`,
      ...(lastModified ? { lastModified } : {}),
      ...route,
      ...(images ? { images: images.map((image) => `${SITE_URL}${image}`) } : {}),
    }
  })
}
