import CitySubpageHeader from '@/components/CitySubpageHeader'
import Footer from '@/components/Footer'
import CityTabbedList from '@/components/CityTabbedList'

const tabs = [
  { value: 'all', label: '全部', dataArea: 'all' },
  { value: '展望台', label: '展望台', dataArea: '展望台' },
  { value: '主題類', label: '主題類', dataArea: '主題類' },
  { value: '親子類', label: '親子類', dataArea: '親子類' },
  { value: '水族館', label: '水族館', dataArea: '水族館' },
]
const cards = [
  { title: 'SHIBUYA SKY', meta: '展望台', area: '展望台', datasetKey: 'title' as const, datasetValue: 'SHIBUYA SKY', actions: [{ label: 'KKDAY', href: 'https://www.kkday.com/zh-tw/product/133300-shibuya-sky-observatory-e-ticket-tokyo?cid=22312', className: 'btn primary', event: 'osakaticket_ShibuyaSkyKKday', platform: 'KKDAY', section: 'ticket_card' }, { label: 'KLOOK', href: 'https://www.klook.com/zh-TW/activity/70672-shibuya-sky-tokyo/?aid=93798', className: 'btn', event: 'osakaticket_ShibuyaSkyKLOOK', platform: 'KLOOK', section: 'ticket_card' }, { label: 'Trip', href: 'https://tw.trip.com/travel-guide/attraction/tokyo/shibuya-sky-136018827/?Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7239738', className: 'btn', event: 'osakaticket_ShibuyaSkyTrip', platform: 'Trip', section: 'ticket_card' }] },
  { title: '晴空塔', meta: '展望台', area: '展望台', datasetKey: 'title' as const, datasetValue: '晴空塔', actions: [{ label: 'KKDAY', href: 'https://www.kkday.com/zh-tw/product/10759-tokyo-skytree-observatory-advance-ticket-japan?cid=22312', className: 'btn primary', event: 'osakaticket_SkyTreeKKday', platform: 'KKDAY', section: 'ticket_card' }, { label: 'KLOOK', href: 'https://www.klook.com/zh-TW/activity/41352-tokyo-skytree/?aid=93798', className: 'btn', event: 'osakaticket_SkyTreeKLOOK', platform: 'KLOOK', section: 'ticket_card' }, { label: 'Trip', href: 'https://tw.trip.com/travel-guide/attraction/tokyo/tokyo-skytree-91422/?Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7239738', className: 'btn', event: 'osakaticket_SkyTreeTrip', platform: 'Trip', section: 'ticket_card' }] },
  { title: '六本木之丘', meta: '展望台', area: '展望台', datasetKey: 'title' as const, datasetValue: '六本木之丘', actions: [{ label: 'KKDAY', href: 'https://www.kkday.com/zh-tw/product/18946-tokyo-city-view-ticket-roppongi-hills-observatory?cid=22312', className: 'btn primary', event: 'osakaticket_RoppongiKKday', platform: 'KKDAY', section: 'ticket_card' }, { label: 'KLOOK', href: 'https://www.klook.com/zh-TW/activity/15762-roppongi-hills-observatory-deck-tokyo/?aid=93798', className: 'btn', event: 'osakaticket_RoppongiKLOOK', platform: 'KLOOK', section: 'ticket_card' }, { label: 'Trip', href: 'https://tw.trip.com/travel-guide/attraction/tokyo/tokyo-city-view-149935797/?Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7239738', className: 'btn', event: 'osakaticket_RoppongiTrip', platform: 'Trip', section: 'ticket_card' }] },
  { title: '東京鐵塔', meta: '展望台', area: '展望台', datasetKey: 'title' as const, datasetValue: '東京鐵塔', actions: [{ label: 'KKDAY', href: 'https://www.kkday.com/zh-tw/product/12271-japan-tokyo-tower-observatory-e-ticket?cid=22312', className: 'btn primary', event: 'osakaticket_TokyoTowerKKday', platform: 'KKDAY', section: 'ticket_card' }, { label: 'KLOOK', href: 'https://www.klook.com/zh-TW/activity/4911-tokyo-tower-main-observatory-ticket-tokyo/?aid=93798', className: 'btn', event: 'osakaticket_TokyoTowerKLOOK', platform: 'KLOOK', section: 'ticket_card' }, { label: 'Trip', href: 'https://tw.trip.com/travel-guide/attraction/tokyo/tokyo-tower-78880/?Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7239738', className: 'btn', event: 'osakaticket_TokyoTowerTrip', platform: 'Trip', section: 'ticket_card' }] },
  { title: '東京迪士尼', meta: '主題類', area: '主題類', datasetKey: 'title' as const, datasetValue: '東京迪士尼', actions: [{ label: 'KKDAY', href: 'https://www.kkday.com/zh-tw/product/19252-tokyo-disney-resort-disneyland-disneysea?cid=22312', className: 'btn primary', event: 'osakaticket_DisneyKKday', platform: 'KKDAY', section: 'ticket_card' }, { label: 'KLOOK', href: 'https://www.klook.com/zh-TW/activity/695-tokyo-disney-resort-1-day-pass-tokyo/?aid=93798', className: 'btn', event: 'osakaticket_DisneyKLOOK', platform: 'KLOOK', section: 'ticket_card' }, { label: 'Trip', href: 'https://tw.trip.com/travel-guide/attraction/urayasu/tokyo-disneyland-10758189/?Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7239738', className: 'btn', event: 'osakaticket_DisneyTrip', platform: 'Trip', section: 'ticket_card' }] },
  { title: '哈利波特影城', meta: '主題類', area: '主題類', datasetKey: 'title' as const, datasetValue: '哈利波特影城', actions: [{ label: 'KKDAY', href: 'https://www.kkday.com/zh-tw/product/144383-warner-bros-studio-tour-tokyo-the-making-of-harry-potter-ticket?cid=22312', className: 'btn primary', event: 'osakaticket_HarryPotterKKday', platform: 'KKDAY', section: 'ticket_card' }, { label: 'KLOOK', href: 'https://www.klook.com/zh-TW/activity/84374-warner-bros-studio-tour-tokyo-making-harry-potter/?aid=93798', className: 'btn', event: 'osakaticket_HarryPotterKLOOK', platform: 'KLOOK', section: 'ticket_card' }, { label: 'Trip', href: 'https://tw.trip.com/travel-guide/attraction/tokyo/the-making-of-harry-potter-warner-bros-studio-tour-tokyo-136452473/?Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7239738', className: 'btn', event: 'osakaticket_HarryPotterTrip', platform: 'Trip', section: 'ticket_card' }] },
  { title: 'TeamLab Planets', meta: '主題類', area: '主題類', datasetKey: 'title' as const, datasetValue: 'TeamLab Planets', actions: [{ label: 'KKDAY', href: 'https://www.kkday.com/zh-tw/product/22396-japan-teamlab-planets-tokyo-ticket?cid=22312', className: 'btn primary', event: 'osakaticket_TeamLabKKday', platform: 'KKDAY', section: 'ticket_card' }, { label: 'KLOOK', href: 'https://www.klook.com/zh-TW/activity/25300-teamlab-planets-toyosu-tokyo-ticket/?aid=93798', className: 'btn', event: 'osakaticket_TeamLabKLOOK', platform: 'KLOOK', section: 'ticket_card' }, { label: 'Trip', href: 'https://tw.trip.com/travel-guide/attraction/tokyo/teamlab-planets-tokyo-61909015/?Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7239738', className: 'btn', event: 'osakaticket_TeamLabTrip', platform: 'Trip', section: 'ticket_card' }] },
  { title: 'TeamLab Borderless', meta: '主題類', area: '主題類', datasetKey: 'title' as const, datasetValue: 'TeamLab Borderless', actions: [{ label: 'KLOOK', href: 'https://www.klook.com/zh-TW/activity/20707-teamlab-borderless-admission-ticket-tokyo/?aid=93798', className: 'btn primary', event: 'osakaticket_BorderlessKLOOK', platform: 'KLOOK', section: 'ticket_card' }, { label: 'Trip', href: 'https://tw.trip.com/travel-guide/attraction/tokyo/teamlab-borderless-mori-building-digital-art-museum-142107812/?Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7239738', className: 'btn', event: 'osakaticket_BorderlessTrip', platform: 'Trip', section: 'ticket_card' }] },
  { title: '便便博物館', meta: '主題類', area: '主題類', datasetKey: 'title' as const, datasetValue: '便便博物館', actions: [{ label: 'KKDAY', href: 'https://www.kkday.com/zh-tw/product/144021-unko-museum-tokyo-admission-ticket-japan?cid=22312', className: 'btn primary', event: 'osakaticket_UnkoMuseumKKday', platform: 'KKDAY', section: 'ticket_card' }, { label: 'KLOOK', href: 'https://www.klook.com/zh-TW/activity/26899-unko-museum-ticket-tokyo/?aid=93798', className: 'btn', event: 'osakaticket_UnkoMuseumKLOOK', platform: 'KLOOK', section: 'ticket_card' }, { label: 'Trip', href: 'https://tw.trip.com/travel-guide/attraction/tokyo/unko-museum-tokyo-141383200/?Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7239738', className: 'btn', event: 'osakaticket_UnkoMuseumTrip', platform: 'Trip', section: 'ticket_card' }] },
  { title: '迷你世界博物館', meta: '親子類', area: '親子類', datasetKey: 'title' as const, datasetValue: '迷你世界博物館', actions: [{ label: 'KKDAY', href: 'https://www.kkday.com/zh-tw/product/115532-small-worlds-tokyo-admission-passport-japan?cid=22312', className: 'btn primary', event: 'osakaticket_SmallWorldsKKday', platform: 'KKDAY', section: 'ticket_card' }, { label: 'KLOOK', href: 'https://www.klook.com/zh-TW/activity/66249-small-worlds-tokyo-admission-passport/?aid=93798', className: 'btn', event: 'osakaticket_SmallWorldsKLOOK', platform: 'KLOOK', section: 'ticket_card' }, { label: 'Trip', href: 'https://tw.trip.com/travel-guide/attraction/tokyo/small-worlds-miniature-museum-84442589/?Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7239738', className: 'btn', event: 'osakaticket_SmallWorldsTrip', platform: 'Trip', section: 'ticket_card' }] },
  { title: '樂高樂園', meta: '親子類', area: '親子類', datasetKey: 'title' as const, datasetValue: '樂高樂園', actions: [{ label: 'KKDAY', href: 'https://www.kkday.com/zh-tw/product/9852-japan-legoland-discovery-center-tokyo-and-madame-tussauds-ticket?cid=22312', className: 'btn primary', event: 'osakaticket_LegolandKKday', platform: 'KKDAY', section: 'ticket_card' }, { label: 'KLOOK', href: 'https://www.klook.com/zh-TW/activity/5563-legoland-discovery-center-tokyo/?aid=93798', className: 'btn', event: 'osakaticket_LegolandKLOOK', platform: 'KLOOK', section: 'ticket_card' }, { label: 'Trip', href: 'https://tw.trip.com/travel-guide/attraction/tokyo/legoland-discovery-center-tokyo-18029735/?Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7239738', className: 'btn', event: 'osakaticket_LegolandTrip', platform: 'Trip', section: 'ticket_card' }] },
  { title: '三麗鷗彩虹樂園', meta: '親子類', area: '親子類', datasetKey: 'title' as const, datasetValue: '三麗鷗彩虹樂園', actions: [{ label: 'KKDAY', href: 'https://www.kkday.com/zh-tw/product/10896-tokyo-sanrio-puroland-ticket?cid=22312', className: 'btn primary', event: 'osakaticket_SanrioKKday', platform: 'KKDAY', section: 'ticket_card' }, { label: 'KLOOK', href: 'https://www.klook.com/zh-TW/activity/2276-sanrio-puroland-tokyo/?aid=93798', className: 'btn', event: 'osakaticket_SanrioKLOOK', platform: 'KLOOK', section: 'ticket_card' }, { label: 'Trip', href: 'https://tw.trip.com/travel-guide/attraction/tama/sanrio-puroland-10759099/?Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7239738', className: 'btn', event: 'osakaticket_SanrioTrip', platform: 'Trip', section: 'ticket_card' }] },
  { title: '墨田水族館', meta: '水族館', area: '水族館', datasetKey: 'title' as const, datasetValue: '墨田水族館', actions: [{ label: 'KKDAY', href: 'https://www.kkday.com/zh-tw/product/149602-sumida-aquarium-admission-tickets-tokyo-skytree?cid=22312', className: 'btn primary', event: 'osakaticket_AquariumKKday', platform: 'KKDAY', section: 'ticket_card' }, { label: 'KLOOK', href: 'https://www.klook.com/zh-TW/activity/59360-tokyo-skytree-sumida-aquarium-combo-ticket/?aid=93798', className: 'btn', event: 'osakaticket_AquariumKLOOK', platform: 'KLOOK', section: 'ticket_card' }, { label: 'Trip', href: 'https://tw.trip.com/travel-guide/attraction/tokyo/sumida-aquarium-24301029/?Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7239738', className: 'btn', event: 'osakaticket_AquariumTrip', platform: 'Trip', section: 'ticket_card' }] },
  { title: '東京銀座藝術水族館', meta: '水族館', area: '水族館', datasetKey: 'title' as const, datasetValue: '東京銀座藝術水族館', actions: [{ label: 'KLOOK', href: 'https://www.klook.com/zh-TW/activity/73977-art-aquarium-ticket-tokyo/?aid=93798', className: 'btn primary', event: 'osakaticket_GinzaAquariumKLOOK', platform: 'KLOOK', section: 'ticket_card' }, { label: 'Trip', href: 'https://tw.trip.com/travel-guide/attraction/tokyo/art-aquarium-museum-136642347/?Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7239738', className: 'btn', event: 'osakaticket_GinzaAquariumTrip', platform: 'Trip', section: 'ticket_card' }] },
  { title: '東京品川水族館', meta: '水族館', area: '水族館', datasetKey: 'title' as const, datasetValue: '東京品川水族館', actions: [{ label: 'KKDAY', href: 'https://www.kkday.com/zh-tw/product/18689-tokyo-maxell-aqua-park-shinagawa-ticket-japan?cid=22312', className: 'btn primary', event: 'osakaticket_MaxellAquaKKday', platform: 'KKDAY', section: 'ticket_card' }, { label: 'KLOOK', href: 'https://www.klook.com/zh-TW/activity/5609-aqua-park-shinagawa-ticket-tokyo/?aid=93798', className: 'btn', event: 'osakaticket_MaxellAquaKLOOK', platform: 'KLOOK', section: 'ticket_card' }, { label: 'Trip', href: 'https://tw.trip.com/travel-guide/attraction/tokyo/maxell-aqua-park-shinagawa-18699600/?Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7239738', className: 'btn', event: 'osakaticket_MaxellAquaTrip', platform: 'Trip', section: 'ticket_card' }] },
  { title: '池袋陽光水族館', meta: '水族館', area: '水族館', datasetKey: 'title' as const, datasetValue: '池袋陽光水族館', actions: [{ label: 'KKDAY', href: 'https://www.kkday.com/zh-tw/product/166262-sunshine-aquarium-60-observation-deck-park-ikebukuro-tokyo?cid=22312', className: 'btn primary', event: 'osakaticket_SunshineAquaKKday', platform: 'KKDAY', section: 'ticket_card' }, { label: 'KLOOK', href: 'https://www.klook.com/zh-TW/activity/14547-sunshine-aquarium-ticket-tokyo/?aid=93798', className: 'btn', event: 'osakaticket_SunshineAquaKLOOK', platform: 'KLOOK', section: 'ticket_card' }, { label: 'Trip', href: 'https://tw.trip.com/travel-guide/attraction/tokyo/sunshine-aquarium-18699584/?Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7239738', className: 'btn', event: 'osakaticket_SunshineAquaTrip', platform: 'Trip', section: 'ticket_card' }] },
]

export default function OsakaTicketPage() {
  return (
    <>
      <CitySubpageHeader backHref="/osaka" eventPrefix="osakaticket" />
      <main className="busan-main transport-main">
        <h1>日本大阪｜票券購買</h1>
        <CityTabbedList tabs={tabs} cards={cards} tabEvent="osaka_ticket_tab" />
      </main>
      <Footer />
    </>
  )
}
