import CitySubpageHeader from '@/components/CitySubpageHeader'
import Footer from '@/components/Footer'
import CityTabbedList from '@/components/CityTabbedList'

const tabs = [
  { value: 'all', label: '全部', dataArea: 'all' },
  { value: '景點攻略', label: '景點攻略', dataArea: '景點攻略' },
  { value: '交通', label: '交通', dataArea: '交通' },
  { value: '行前準備', label: '行前準備', dataArea: '行前準備' },
]
const cards = [
  { title: '六本木點燈｜最佳路線', meta: '景點攻略', area: '景點攻略', datasetKey: 'video' as const, datasetValue: 'RoppongiIllumination', actions: [{ label: 'IG Reels', href: 'https://www.instagram.com/reel/DSfemOTEqbL/', className: 'btn primary', event: 'osakavideo_RoppongiIlluminationIG', platform: 'IG', section: 'video' }, { label: 'YouTube', href: 'https://www.youtube.com/shorts/yZ8eH_jOKYM', className: 'btn', event: 'osakavideo_RoppongiIlluminationYT', platform: 'YouTube', section: 'video' }, { label: '小紅書', href: 'https://xhslink.com/o/2DymZx52KpT', className: 'btn', event: 'osakavideo_RoppongiIlluminationXHS', platform: '小紅書', section: 'video' }] },
  { title: '惠比壽花園點燈｜最佳路線', meta: '景點攻略', area: '景點攻略', datasetKey: 'video' as const, datasetValue: 'HibiyaGardenIllumination', actions: [{ label: 'IG Reels', href: 'https://www.instagram.com/reel/DShsI6gEa8u/', className: 'btn primary', event: 'osakavideo_HibiyaGardenIlluminationIG', platform: 'IG', section: 'video' }, { label: 'YouTube', href: 'https://www.youtube.com/shorts/I6VfBsc9YJE', className: 'btn', event: 'osakavideo_HibiyaGardenIlluminationYT', platform: 'YouTube', section: 'video' }, { label: '小紅書', href: 'https://xhslink.com/o/9qXKYa7AxGZ', className: 'btn', event: 'osakavideo_HibiyaGardenIlluminationXHS', platform: '小紅書', section: 'video' }] },
  { title: '地鐵 vs JR｜攻略', meta: '交通', area: '交通', datasetKey: 'video' as const, datasetValue: 'MetroVSJR', actions: [{ label: 'IG Reels', href: 'https://www.instagram.com/reel/DTVMB2FkTt5/', className: 'btn primary', event: 'osakavideo_MetroVSJRIG', platform: 'IG', section: 'video' }, { label: 'YouTube', href: 'https://www.youtube.com/shorts/xNN5iQLFGcU', className: 'btn', event: 'osakavideo_MetroVSJRYT', platform: 'YouTube', section: 'video' }, { label: '小紅書', href: 'https://xhslink.com/o/3MITM21zfli', className: 'btn', event: 'osakavideo_MetroVSJRXHS', platform: '小紅書', section: 'video' }] },
  { title: 'JR vs 新幹線｜攻略', meta: '交通', area: '交通', datasetKey: 'video' as const, datasetValue: 'JRVSXinganxian', actions: [{ label: 'IG Reels', href: 'https://www.instagram.com/reel/DVBVYRckTUG/', className: 'btn primary', event: 'osakavideo_JRVSXGXIG', platform: 'IG', section: 'video' }, { label: 'YouTube', href: 'https://www.youtube.com/shorts/j_Ws48TTzbE', className: 'btn', event: 'osakavideo_JRVSXGXYT', platform: 'YouTube', section: 'video' }, { label: '小紅書', href: 'https://xhslink.com/o/2h8p1nd33PE', className: 'btn', event: 'osakavideo_JRVSXGXXHS', platform: '小紅書', section: 'video' }] },
  { title: '東京地鐵票券｜攻略', meta: '交通', area: '交通', datasetKey: 'video' as const, datasetValue: 'TokyoSubwayTicket', actions: [{ label: 'IG Reels', href: 'https://www.instagram.com/reel/DTnNqDgkZOm/', className: 'btn primary', event: 'osakavideo_TokyoSubwayTicketIG', platform: 'IG', section: 'video' }, { label: 'YouTube', href: 'https://www.youtube.com/shorts/dz2aJtW3y9c', className: 'btn', event: 'osakavideo_TokyoSubwayTicketYT', platform: 'YouTube', section: 'video' }, { label: '小紅書', href: 'https://xhslink.com/o/3CIm2CzXmSI', className: 'btn', event: 'osakavideo_TokyoSubwayTicketXHS', platform: '小紅書', section: 'video' }] },
  { title: '東京地鐵搭乘｜3個重點', meta: '交通', area: '交通', datasetKey: 'video' as const, datasetValue: 'TokyoSubwayTips', actions: [{ label: 'IG Reels', href: 'https://www.instagram.com/reel/DT5PNXdk4DM/', className: 'btn primary', event: 'osakavideo_TokyoSubwayTipsIG', platform: 'IG', section: 'video' }, { label: 'YouTube', href: 'https://www.youtube.com/shorts/9KtpGIZE9wk', className: 'btn', event: 'osakavideo_TokyoSubwayTipsYT', platform: 'YouTube', section: 'video' }, { label: '小紅書', href: 'https://xhslink.com/o/4nx9iQs8ukJ', className: 'btn', event: 'osakavideo_TokyoSubwayTipsXHS', platform: '小紅書', section: 'video' }] },
  { title: '成田機場到市區｜3種方式', meta: '交通', area: '交通', datasetKey: 'video' as const, datasetValue: 'NaritaAirportToCity', actions: [{ label: 'IG Reels', href: 'https://www.instagram.com/reel/DULQxKUkVR2/', className: 'btn primary', event: 'osakavideo_NaritaAirportToCityIG', platform: 'IG', section: 'video' }, { label: 'YouTube', href: 'https://www.youtube.com/shorts/vdFwmQd8CLQ', className: 'btn', event: 'osakavideo_NaritaAirportToCityYT', platform: 'YouTube', section: 'video' }, { label: '小紅書', href: 'https://xhslink.com/o/6SAdU1cGAHr', className: 'btn', event: 'osakavideo_NaritaAirportToCityXHS', platform: '小紅書', section: 'video' }] },
  { title: '成田機場到市區｜最便宜方式', meta: '交通', area: '交通', datasetKey: 'video' as const, datasetValue: 'NaritaAirportToCity2', actions: [{ label: 'IG Reels', href: 'https://www.instagram.com/reel/DUdSUu1kdXn/', className: 'btn primary', event: 'osakavideo_NaritaAirportToCity2IG', platform: 'IG', section: 'video' }, { label: 'YouTube', href: 'https://www.youtube.com/shorts/rKJejwOTIw0', className: 'btn', event: 'osakavideo_NaritaAirportToCity2YT', platform: 'YouTube', section: 'video' }, { label: '小紅書', href: 'https://xhslink.com/o/AgcJoBlsdj8', className: 'btn', event: 'osakavideo_NaritaAirportToCity2XHS', platform: '小紅書', section: 'video' }] },
  { title: '羽田機場到市區｜3種方式', meta: '交通', area: '交通', datasetKey: 'video' as const, datasetValue: 'HNDToCity', actions: [{ label: 'IG Reels', href: 'https://www.instagram.com/reel/DUvT5Etkf4f/', className: 'btn primary', event: 'osakavideo_HNDToCityIG', platform: 'IG', section: 'video' }, { label: 'YouTube', href: 'https://www.youtube.com/shorts/fTtfgB93DE4', className: 'btn', event: 'osakavideo_HNDToCityYT', platform: 'YouTube', section: 'video' }, { label: '小紅書', href: 'https://xhslink.com/o/5Un3Rc5yHnU', className: 'btn', event: 'osakavideo_HNDToCityXHS', platform: '小紅書', section: 'video' }] },
  { title: 'Visit Japan Web｜入境卡填寫', meta: '行前準備', area: '行前準備', datasetKey: 'video' as const, datasetValue: 'VisitJapanWeb', actions: [{ label: 'IG Reels', href: 'https://www.instagram.com/reel/DSxI34Nkebp/', className: 'btn primary', event: 'osakavideo_visitjapanwebIG', platform: 'IG', section: 'video' }, { label: 'YouTube', href: 'https://www.youtube.com/shorts/DWKvXvEHyKk', className: 'btn', event: 'osakavideo_visitjapanwebYT', platform: 'YouTube', section: 'video' }, { label: '小紅書', href: 'https://xhslink.com/o/3g4dVW46U4I', className: 'btn', event: 'osakavideo_visitjapanwebXHS', platform: '小紅書', section: 'video' }] },
  { title: '日幣換匯攻略', meta: '行前準備', area: '行前準備', datasetKey: 'video' as const, datasetValue: 'JPYExchange', actions: [{ label: 'IG Reels', href: 'https://www.instagram.com/reel/DTDKcCoEZBS/', className: 'btn primary', event: 'osakavideo_JPYExchangeIG', platform: 'IG', section: 'video' }, { label: 'YouTube', href: 'https://www.youtube.com/shorts/FfMj7w2R7BA', className: 'btn', event: 'osakavideo_JPYExchangeYT', platform: 'YouTube', section: 'video' }, { label: '小紅書', href: 'https://xhslink.com/o/83JoRvRQFSc', className: 'btn', event: 'osakavideo_JPYExchangeXHS', platform: '小紅書', section: 'video' }] },
]

export default function OsakaVideoPage() {
  return (
    <>
      <CitySubpageHeader backHref="/osaka" eventPrefix="osakavideo" />
      <main className="busan-main transport-main">
        <h1>短影片合輯｜認識大阪・景點攻略・行前準備</h1>
        <CityTabbedList tabs={tabs} cards={cards} tabEvent="osaka_video_tab" />
      </main>
      <Footer />
    </>
  )
}
