import CitySubpageHeader from '@/components/CitySubpageHeader'
import Footer from '@/components/Footer'
import CityTabbedList from '@/components/CityTabbedList'

const tabs = [
  { value: 'all', label: '全部', dataArea: 'all' },
  { value: '上野站', label: '上野站', dataArea: '上野站' },
  { value: '淺草寺', label: '淺草寺', dataArea: '淺草寺' },
  { value: '東京車站', label: '東京車站', dataArea: '東京車站' },
  { value: '新宿站', label: '新宿站', dataArea: '新宿站' },
  { value: '涉谷站', label: '涉谷站', dataArea: '涉谷站' },
]
const cards = [
  { title: '明恩上野', meta: '上野站｜5星級、清幽/高級/寬敞/廚房/設備齊全', area: '上野站', datasetKey: 'hotel' as const, datasetValue: '明恩上野', actions: [{ label: 'Agoda', href: 'https://www.agoda.com/partners/partnersearch.aspx?pcs=1&cid=1945734&hid=52134686', className: 'btn primary', event: 'osakahotel_Ueno1Agoda', platform: 'Agoda', section: 'hotel_card' }, { label: 'Trip', href: 'https://tw.trip.com/hotels/detail/?cityId=228&hotelId=64218295&Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7207517', className: 'btn', event: 'osakahotel_Ueno1Trip', platform: 'Trip', section: 'hotel_card' }, { label: '地圖', href: 'https://maps.app.goo.gl/7Rh9hToJJYpmqvfH7', className: 'btn', event: 'osakahotel_Ueno1map', platform: 'Maps', section: 'hotel_card' }] },
  { title: '上野曼迪高級公寓', meta: '上野站｜4星級、寬敞/乾淨/安靜/家庭', area: '上野站', datasetKey: 'hotel' as const, datasetValue: '上野曼迪高級公寓', actions: [{ label: 'Agoda', href: 'https://www.agoda.com/partners/partnersearch.aspx?pcs=1&cid=1945734&hid=21816880', className: 'btn primary', event: 'osakahotel_Ueno2Agoda', platform: 'Agoda', section: 'hotel_card' }, { label: 'Trip', href: 'https://tw.trip.com/hotels/detail/?cityId=228&hotelId=78158674&Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7207517', className: 'btn', event: 'osakahotel_Ueno2Trip', platform: 'Trip', section: 'hotel_card' }, { label: '地圖', href: 'https://maps.app.goo.gl/7SNvgcucJGSKdAnh9', className: 'btn', event: 'osakahotel_Ueno2map', platform: 'Maps', section: 'hotel_card' }] },
  { title: '東京上野諾加上飯店', meta: '上野站｜4星級、寬敞/現代/舒適/交通便利', area: '上野站', datasetKey: 'hotel' as const, datasetValue: '東京上野諾加上飯店', actions: [{ label: 'Agoda', href: 'https://www.agoda.com/partners/partnersearch.aspx?pcs=1&cid=1945734&hid=5760934', className: 'btn primary', event: 'osakahotel_Ueno3Agoda', platform: 'Agoda', section: 'hotel_card' }, { label: 'Trip', href: 'https://tw.trip.com/hotels/detail/?cityId=228&hotelId=21890132&Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7207517', className: 'btn', event: 'osakahotel_Ueno3Trip', platform: 'Trip', section: 'hotel_card' }, { label: '地圖', href: 'https://maps.app.goo.gl/FsMHpKMnpULSyDebA', className: 'btn', event: 'osakahotel_Ueno3map', platform: 'Maps', section: 'hotel_card' }] },
  { title: '三井花園飯店', meta: '上野站｜4星級、寬敞/現代/乾淨/交通便利', area: '上野站', datasetKey: 'hotel' as const, datasetValue: '三井花園飯店', actions: [{ label: 'Agoda', href: 'https://www.agoda.com/partners/partnersearch.aspx?pcs=1&cid=1945734&hid=222614', className: 'btn primary', event: 'osakahotel_Ueno4Agoda', platform: 'Agoda', section: 'hotel_card' }, { label: 'Trip', href: 'https://tw.trip.com/hotels/detail/?cityId=228&hotelId=688243&Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7207517', className: 'btn', event: 'osakahotel_Ueno4Trip', platform: 'Trip', section: 'hotel_card' }, { label: '地圖', href: 'https://maps.app.goo.gl/jHxkF2A8Y4vTJsaU6', className: 'btn', event: 'osakahotel_Ueno4map', platform: 'Maps', section: 'hotel_card' }] },
  { title: '淺草田原町KOKO飯店住宅', meta: '淺草寺｜4星級、寬敞/小廚房/用餐區/交通便利', area: '淺草寺', datasetKey: 'hotel' as const, datasetValue: '淺草田原町KOKO飯店住宅', actions: [{ label: 'Agoda', href: 'https://www.agoda.com/partners/partnersearch.aspx?pcs=1&cid=1945734&hid=32355474', className: 'btn primary', event: 'osakahotel_Sensoji1Agoda', platform: 'Agoda', section: 'hotel_card' }, { label: 'Trip', href: 'https://tw.trip.com/hotels/detail/?cityId=228&hotelId=94472393&Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7207517', className: 'btn', event: 'osakahotel_Sensoji1Trip', platform: 'Trip', section: 'hotel_card' }, { label: '地圖', href: 'https://maps.app.goo.gl/AVwYsdvH9Bj6RRft7', className: 'btn', event: 'osakahotel_Sensoji1map', platform: 'Maps', section: 'hotel_card' }] },
  { title: '淺草雷門休雷克蓋特飯店', meta: '淺草寺｜4星級、屋頂酒吧/寬敞/乾淨/交通便利', area: '淺草寺', datasetKey: 'hotel' as const, datasetValue: '淺草雷門休雷克蓋特飯店', actions: [{ label: 'Agoda', href: 'https://www.agoda.com/partners/partnersearch.aspx?pcs=1&cid=1945734&hid=344281', className: 'btn primary', event: 'osakahotel_Sensoji2Agoda', platform: 'Agoda', section: 'hotel_card' }, { label: 'Trip', href: 'https://tw.trip.com/hotels/detail/?cityId=228&hotelId=686539&Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7207517', className: 'btn', event: 'osakahotel_Sensoji2Trip', platform: 'Trip', section: 'hotel_card' }, { label: '地圖', href: 'https://maps.app.goo.gl/4BacTKaF6zS1QUrR8', className: 'btn', event: 'osakahotel_Sensoji2map', platform: 'Maps', section: 'hotel_card' }] },
  { title: '淺草雷門竹之宿旅館', meta: '淺草寺｜4星級、安靜/乾淨/交通便利/CP值高', area: '淺草寺', datasetKey: 'hotel' as const, datasetValue: '淺草雷門竹之宿旅館', actions: [{ label: 'Agoda', href: 'https://www.agoda.com/partners/partnersearch.aspx?pcs=1&cid=1945734&hid=18957641', className: 'btn primary', event: 'osakahotel_Sensoji3Agoda', platform: 'Agoda', section: 'hotel_card' }, { label: 'Trip', href: 'https://tw.trip.com/hotels/detail/?cityId=228&hotelId=48022031&Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7207517', className: 'btn', event: 'osakahotel_Sensoji3Trip', platform: 'Trip', section: 'hotel_card' }, { label: '地圖', href: 'https://maps.app.goo.gl/BDUZ2NDMt45Q6ckA9', className: 'btn', event: 'osakahotel_Sensoji3map', platform: 'Maps', section: 'hotel_card' }] },
  { title: '東京淺草遠東鄉村飯店', meta: '淺草寺｜3星級、乾淨舒適/交通便利/CP值高', area: '淺草寺', datasetKey: 'hotel' as const, datasetValue: '東京淺草遠東鄉村飯店', actions: [{ label: 'Agoda', href: 'https://www.agoda.com/partners/partnersearch.aspx?pcs=1&cid=1945734&hl=zh-tw&hid=37262185', className: 'btn primary', event: 'osakahotel_Sensoji4Agoda', platform: 'Agoda', section: 'hotel_card' }, { label: 'Trip', href: 'https://tw.trip.com/hotels/detail/?cityId=228&hotelId=107168939&Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7207517', className: 'btn', event: 'osakahotel_Sensoji4Trip', platform: 'Trip', section: 'hotel_card' }, { label: '地圖', href: 'https://maps.app.goo.gl/q6PcH6mcBTSk5abF7', className: 'btn', event: 'osakahotel_Sensoji4map', platform: 'Maps', section: 'hotel_card' }] },
  { title: '千禧 三井花園飯店 東京/銀座', meta: '東京車站｜5星級、寬敞/乾淨/美景/交通便利', area: '東京車站', datasetKey: 'hotel' as const, datasetValue: '千禧 三井花園飯店 東京/銀座', actions: [{ label: 'Agoda', href: 'https://www.agoda.com/partners/partnersearch.aspx?pcs=1&cid=1945734&hid=648873', className: 'btn primary', event: 'osakahotel_TokyoStation1Agoda', platform: 'Agoda', section: 'hotel_card' }, { label: 'Trip', href: 'https://tw.trip.com/hotels/detail/?cityId=228&hotelId=1683161&Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7207517', className: 'btn', event: 'osakahotel_TokyoStation1Trip', platform: 'Trip', section: 'hotel_card' }, { label: '地圖', href: 'https://maps.app.goo.gl/FjYR8chuJiWiJVRG6', className: 'btn', event: 'osakahotel_TokyoStation1map', platform: 'Maps', section: 'hotel_card' }] },
  { title: '東京龍名館飯店', meta: '東京車站｜4星級、早餐佳/現代/服務好/交通便利', area: '東京車站', datasetKey: 'hotel' as const, datasetValue: '東京龍名館飯店', actions: [{ label: 'Agoda', href: 'https://www.agoda.com/partners/partnersearch.aspx?pcs=1&cid=1945734&hid=164430', className: 'btn primary', event: 'osakahotel_TokyoStation2Agoda', platform: 'Agoda', section: 'hotel_card' }, { label: 'Trip', href: 'https://tw.trip.com/hotels/detail/?cityId=228&hotelId=688171&Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7207517', className: 'btn', event: 'osakahotel_TokyoStation2Trip', platform: 'Trip', section: 'hotel_card' }, { label: '地圖', href: 'https://maps.app.goo.gl/1WjGgkxsh1ZcLezVA', className: 'btn', event: 'osakahotel_TokyoStation2map', platform: 'Maps', section: 'hotel_card' }] },
  { title: '東京京橋雷姆飯店', meta: '東京車站｜4星級、按摩椅/配備完善/交通便利', area: '東京車站', datasetKey: 'hotel' as const, datasetValue: '東京京橋雷姆飯店', actions: [{ label: 'Agoda', href: 'https://www.agoda.com/partners/partnersearch.aspx?pcs=1&cid=1945734&hid=5760819', className: 'btn primary', event: 'osakahotel_TokyoStation3Agoda', platform: 'Agoda', section: 'hotel_card' }, { label: 'Trip', href: 'https://tw.trip.com/hotels/detail/?cityId=228&hotelId=23747919&Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7207517', className: 'btn', event: 'osakahotel_TokyoStation3Trip', platform: 'Trip', section: 'hotel_card' }, { label: '地圖', href: 'https://maps.app.goo.gl/Jv6zk6wWvPcftKkEA', className: 'btn', event: 'osakahotel_TokyoStation3map', platform: 'Maps', section: 'hotel_card' }] },
  { title: '東京銀座金特薩酒店', meta: '東京車站｜3星級、位置優越/現代設計/交通便利', area: '東京車站', datasetKey: 'hotel' as const, datasetValue: '東京銀座金特薩酒店', actions: [{ label: 'Agoda', href: 'https://www.agoda.com/partners/partnersearch.aspx?pcs=1&cid=1945734&hid=8649501', className: 'btn primary', event: 'osakahotel_TokyoStation4Agoda', platform: 'Agoda', section: 'hotel_card' }, { label: 'Trip', href: 'https://tw.trip.com/hotels/detail/?cityId=228&hotelId=42572779&Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7207517', className: 'btn', event: 'osakahotel_TokyoStation4Trip', platform: 'Trip', section: 'hotel_card' }, { label: '地圖', href: 'https://maps.app.goo.gl/U3pv49dDcRUu1b8d7', className: 'btn', event: 'osakahotel_TokyoStation4map', platform: 'Maps', section: 'hotel_card' }] },
  { title: '東京京王廣場飯店', meta: '新宿站｜5星級、床舒適/寬敞乾淨/位置優越/交通便利', area: '新宿站', datasetKey: 'hotel' as const, datasetValue: '東京京王廣場飯店', actions: [{ label: 'Agoda', href: 'https://www.agoda.com/partners/partnersearch.aspx?pcs=1&cid=1945734&hid=7263', className: 'btn primary', event: 'osakahotel_Shinjuku1Agoda', platform: 'Agoda', section: 'hotel_card' }, { label: 'Trip', href: 'https://tw.trip.com/hotels/detail/?cityId=228&hotelId=994639&Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7207517', className: 'btn', event: 'osakahotel_Shinjuku1Trip', platform: 'Trip', section: 'hotel_card' }, { label: '地圖', href: 'https://maps.app.goo.gl/kWPpBNYdnAdTBdUMA', className: 'btn', event: 'osakahotel_Shinjuku1map', platform: 'Maps', section: 'hotel_card' }] },
  { title: '格拉斯麗新宿酒店', meta: '新宿站｜4星級、哥吉拉/乾淨/位置優越/交通便利', area: '新宿站', datasetKey: 'hotel' as const, datasetValue: '格拉斯麗新宿酒店', actions: [{ label: 'Agoda', href: 'https://www.agoda.com/partners/partnersearch.aspx?pcs=1&cid=1945734&hid=706347', className: 'btn primary', event: 'osakahotel_Shinjuku2Agoda', platform: 'Agoda', section: 'hotel_card' }, { label: 'Trip', href: 'https://tw.trip.com/hotels/detail/?cityId=228&hotelId=1841600&Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7207517', className: 'btn', event: 'osakahotel_Shinjuku2Trip', platform: 'Trip', section: 'hotel_card' }, { label: '地圖', href: 'https://maps.app.goo.gl/NstvVv8ziDj3s1XJ7', className: 'btn', event: 'osakahotel_Shinjuku2map', platform: 'Maps', section: 'hotel_card' }] },
  { title: 'WPÜ飯店新宿', meta: '新宿站｜3星級、位置優越/交通便利/CP值高', area: '新宿站', datasetKey: 'hotel' as const, datasetValue: 'WPÜ飯店新宿', actions: [{ label: 'Agoda', href: 'https://www.agoda.com/partners/partnersearch.aspx?pcs=1&cid=1945734&hid=39339883', className: 'btn primary', event: 'osakahotel_Shinjuku3Agoda', platform: 'Agoda', section: 'hotel_card' }, { label: 'Trip', href: 'https://tw.trip.com/hotels/detail/?cityId=228&hotelId=108415888&Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7207517', className: 'btn', event: 'osakahotel_Shinjuku3Trip', platform: 'Trip', section: 'hotel_card' }, { label: '地圖', href: 'https://maps.app.goo.gl/ZDHZ1nzUjH3vSmo48', className: 'btn', event: 'osakahotel_Shinjuku3map', platform: 'Maps', section: 'hotel_card' }] },
  { title: '普樂美雅飯店-CABIN-新宿', meta: '新宿站｜3星級、位置優越/交通便利/小資族', area: '新宿站', datasetKey: 'hotel' as const, datasetValue: '普樂美雅飯店-CABIN-新宿', actions: [{ label: 'Agoda', href: 'https://www.agoda.com/partners/partnersearch.aspx?pcs=1&cid=1945734&hid=43346', className: 'btn primary', event: 'osakahotel_Shinjuku4Agoda', platform: 'Agoda', section: 'hotel_card' }, { label: 'Trip', href: 'https://tw.trip.com/hotels/detail/?cityId=228&hotelId=1436735&Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7207517', className: 'btn', event: 'osakahotel_Shinjuku4Trip', platform: 'Trip', section: 'hotel_card' }, { label: '地圖', href: 'https://maps.app.goo.gl/utK97Jr3hiSPk63R6', className: 'btn', event: 'osakahotel_Shinjuku4map', platform: 'Maps', section: 'hotel_card' }] },
  { title: '東京澀谷英迪格飯店', meta: '涉谷站｜5星級、現代設施/乾淨寬敞/精華地段/交通便利', area: '涉谷站', datasetKey: 'hotel' as const, datasetValue: '東京澀谷英迪格飯店', actions: [{ label: 'Agoda', href: 'https://www.agoda.com/partners/partnersearch.aspx?pcs=1&cid=1945734&hid=37465373', className: 'btn primary', event: 'osakahotel_Shibuya1Agoda', platform: 'Agoda', section: 'hotel_card' }, { label: 'Trip', href: 'https://tw.trip.com/hotels/detail/?cityId=228&hotelId=104994675&Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7207517', className: 'btn', event: 'osakahotel_Shibuya1Trip', platform: 'Trip', section: 'hotel_card' }, { label: '地圖', href: 'https://maps.app.goo.gl/DFLyiRSnBJ9NmDTZ6', className: 'btn', event: 'osakahotel_Shibuya1map', platform: 'Maps', section: 'hotel_card' }] },
  { title: '澀谷東急卓越大飯店', meta: '涉谷站｜4星級、舒適/服務好/位置優越/交通便利', area: '涉谷站', datasetKey: 'hotel' as const, datasetValue: '澀谷東急卓越大飯店', actions: [{ label: 'Agoda', href: 'https://www.agoda.com/partners/partnersearch.aspx?pcs=1&cid=1945734&hid=7005', className: 'btn primary', event: 'osakahotel_Shibuya2Agoda', platform: 'Agoda', section: 'hotel_card' }, { label: 'Trip', href: 'https://tw.trip.com/hotels/detail/?cityId=228&hotelId=994472&Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7207517', className: 'btn', event: 'osakahotel_Shibuya2Trip', platform: 'Trip', section: 'hotel_card' }, { label: '地圖', href: 'https://maps.app.goo.gl/zsnpyMBGNqeJRjut9', className: 'btn', event: 'osakahotel_Shibuya2map', platform: 'Maps', section: 'hotel_card' }] },
  { title: '澀谷溪流酒店', meta: '涉谷站｜4星級、乾淨寬敞/位置優越/交通便利', area: '涉谷站', datasetKey: 'hotel' as const, datasetValue: '澀谷溪流酒店', actions: [{ label: 'Agoda', href: 'https://www.agoda.com/partners/partnersearch.aspx?pcs=1&cid=1945734&hid=5358526', className: 'btn primary', event: 'osakahotel_Shibuya3Agoda', platform: 'Agoda', section: 'hotel_card' }, { label: 'Trip', href: 'https://tw.trip.com/hotels/detail/?cityId=228&hotelId=22564082&Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7207517', className: 'btn', event: 'osakahotel_Shibuya3Trip', platform: 'Trip', section: 'hotel_card' }, { label: '地圖', href: 'https://maps.app.goo.gl/t3eThmCicEQpnx3L9', className: 'btn', event: 'osakahotel_Shibuya3map', platform: 'Maps', section: 'hotel_card' }] },
  { title: '澀谷飯店EN', meta: '涉谷站｜3星級、乾淨舒適/交通便利/CP值高', area: '涉谷站', datasetKey: 'hotel' as const, datasetValue: '澀谷飯店EN', actions: [{ label: 'Agoda', href: 'https://www.agoda.com/partners/partnersearch.aspx?pcs=1&cid=1945734&hid=390255', className: 'btn primary', event: 'osakahotel_Shibuya4Agoda', platform: 'Agoda', section: 'hotel_card' }, { label: 'Trip', href: 'https://tw.trip.com/hotels/detail/?cityId=228&hotelId=688139&Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D7207517', className: 'btn', event: 'osakahotel_Shibuya4Trip', platform: 'Trip', section: 'hotel_card' }, { label: '地圖', href: 'https://maps.app.goo.gl/Squ3f5ViYFh1yGea6', className: 'btn', event: 'osakahotel_Shibuya4map', platform: 'Maps', section: 'hotel_card' }] },
]

export default function OsakaHotelPage() {
  return (
    <>
      <CitySubpageHeader backHref="/osaka" eventPrefix="osakahotel" />
      <main className="busan-main transport-main">
        <h1 className="sr-only">大阪住宿精選｜JieJourneys(旅杰)</h1>
        <h2>日本大阪住宿精選</h2>
        <CityTabbedList tabs={tabs} cards={cards} tabEvent="osaka_hotel_tab" />
      </main>
      <Footer />
    </>
  )
}
