-- Persist hotel affiliate observations separately from planner books, while
-- only exposing identities that have been explicitly verified. Planner owners
-- may contribute candidates through a valid edit token, but cannot promote a
-- candidate into the globally trusted lookup table.

begin;

create table if not exists public.planner_hotel_affiliate_identities (
  google_place_id text primary key,
  canonical_names jsonb not null default '[]'::jsonb,
  latitude double precision,
  longitude double precision,
  country_code text,
  agoda_hotel_id text,
  agoda_hotel_name text,
  agoda_source_url text,
  trip_hotel_id text,
  trip_hotel_name text,
  trip_source_url text,
  verification_status text not null default 'verified',
  verified_by text not null,
  verified_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint planner_hotel_affiliate_identity_place_id_check
    check (google_place_id ~ '^[A-Za-z0-9_-]{8,180}$'),
  constraint planner_hotel_affiliate_identity_names_check
    check (jsonb_typeof(canonical_names) = 'array'),
  constraint planner_hotel_affiliate_identity_latitude_check
    check (latitude is null or latitude between -90 and 90),
  constraint planner_hotel_affiliate_identity_longitude_check
    check (longitude is null or longitude between -180 and 180),
  constraint planner_hotel_affiliate_identity_country_check
    check (country_code is null or country_code ~ '^[A-Z]{2}$'),
  constraint planner_hotel_affiliate_identity_agoda_id_check
    check (agoda_hotel_id is null or agoda_hotel_id ~ '^[0-9]{3,}$'),
  constraint planner_hotel_affiliate_identity_trip_id_check
    check (trip_hotel_id is null or trip_hotel_id ~ '^[0-9]{3,}$'),
  constraint planner_hotel_affiliate_identity_provider_check
    check (agoda_hotel_id is not null or trip_hotel_id is not null),
  constraint planner_hotel_affiliate_identity_status_check
    check (verification_status in ('verified', 'disabled'))
);

create table if not exists public.planner_hotel_affiliate_candidates (
  id bigint generated by default as identity primary key,
  google_place_id text not null,
  provider text not null,
  hotel_id text not null,
  href text not null,
  google_place_name text,
  place_name text,
  latitude double precision,
  longitude double precision,
  source_book_id text,
  source_place_id text,
  status text not null default 'pending',
  seen_count integer not null default 1,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  constraint planner_hotel_affiliate_candidate_place_id_check
    check (google_place_id ~ '^[A-Za-z0-9_-]{8,180}$'),
  constraint planner_hotel_affiliate_candidate_provider_check
    check (provider in ('Agoda', 'Trip')),
  constraint planner_hotel_affiliate_candidate_hotel_id_check
    check (hotel_id ~ '^[0-9]{3,}$'),
  constraint planner_hotel_affiliate_candidate_href_check
    check (href ~ '^https://'),
  constraint planner_hotel_affiliate_candidate_latitude_check
    check (latitude is null or latitude between -90 and 90),
  constraint planner_hotel_affiliate_candidate_longitude_check
    check (longitude is null or longitude between -180 and 180),
  constraint planner_hotel_affiliate_candidate_status_check
    check (status in ('pending', 'promoted', 'conflict', 'rejected')),
  unique (google_place_id, provider, hotel_id)
);

create index if not exists planner_hotel_affiliate_candidates_review_idx
  on public.planner_hotel_affiliate_candidates (status, last_seen_at desc);

alter table public.planner_hotel_affiliate_identities enable row level security;
alter table public.planner_hotel_affiliate_candidates enable row level security;
revoke all on public.planner_hotel_affiliate_identities from public, anon, authenticated;
revoke all on public.planner_hotel_affiliate_candidates from public, anon, authenticated;

-- Public callers can only read an already verified identity by its exact
-- Google Place ID. Coordinates and country are checked again by the app.
create or replace function public.planner_hotel_affiliate_identity_lookup(
  p_google_place_id text,
  p_latitude double precision default null,
  p_longitude double precision default null,
  p_country_code text default null
)
returns table (
  google_place_id text,
  canonical_names jsonb,
  latitude double precision,
  longitude double precision,
  country_code text,
  agoda_hotel_id text,
  agoda_hotel_name text,
  agoda_source_url text,
  trip_hotel_id text,
  trip_hotel_name text,
  trip_source_url text,
  verified_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select
    i.google_place_id,
    i.canonical_names,
    i.latitude,
    i.longitude,
    i.country_code,
    i.agoda_hotel_id,
    i.agoda_hotel_name,
    i.agoda_source_url,
    i.trip_hotel_id,
    i.trip_hotel_name,
    i.trip_source_url,
    i.verified_at
  from public.planner_hotel_affiliate_identities i
  where i.google_place_id = trim(coalesce(p_google_place_id, ''))
    and i.verification_status = 'verified'
    and (
      nullif(upper(trim(coalesce(p_country_code, ''))), '') is null
      or i.country_code is null
      or i.country_code = upper(trim(p_country_code))
    )
    and (
      p_latitude is null
      or p_longitude is null
      or i.latitude is null
      or i.longitude is null
      or 6371000 * acos(
        least(
          1.0,
          greatest(
            -1.0,
            cos(radians(p_latitude)) * cos(radians(i.latitude)) *
              cos(radians(i.longitude) - radians(p_longitude)) +
            sin(radians(p_latitude)) * sin(radians(i.latitude))
          )
        )
      ) <= 500
    )
  limit 1;
$$;

revoke all on function public.planner_hotel_affiliate_identity_lookup(text, double precision, double precision, text) from public;
grant execute on function public.planner_hotel_affiliate_identity_lookup(text, double precision, double precision, text) to anon, authenticated;

-- Replaces the narrow planner merge RPC and adds an observation write before
-- its existing duplicate-link checks. The observation is never trusted on its
-- own; promotion is restricted to service_role below.
create or replace function public.planner_book_add_affiliate_link(
  p_id text,
  p_edit_token text,
  p_place_id text,
  p_provider text,
  p_href text
)
returns table (id text, read_token text, updated_at timestamptz, changed boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  current_custom_places jsonb;
  current_user_links jsonb;
  current_place jsonb;
  current_place_links jsonb;
  next_place_links jsonb;
  provider_domain text;
  observed_google_place_id text;
  observed_hotel_id text;
  observed_google_place_name text;
  observed_place_name text;
  observed_latitude_text text;
  observed_longitude_text text;
  observed_latitude double precision;
  observed_longitude double precision;
  observed_status text := 'pending';
  observed_lodging boolean := false;
begin
  if p_edit_token is null
    or p_edit_token !~ '^([a-f0-9]{64}|[A-Za-z0-9_-]{22})$'
    or p_id is null
    or p_id !~ '^[A-Za-z0-9_-]{7,32}$'
    or p_place_id is null
    or p_place_id !~ '^custom:[A-Za-z0-9_-]{1,80}$'
    or p_provider is null
    or p_provider not in ('Agoda', 'Trip')
    or p_href is null
    or coalesce(length(trim(p_href)), 0) > 500
    or p_href !~ '^https://' then
    return;
  end if;

  provider_domain := case when p_provider = 'Agoda' then 'agoda\.com' else 'trip\.com' end;
  if lower(p_href) !~ ('^https://([a-z0-9-]+\.)*' || provider_domain || '(/|$)') then
    return;
  end if;

  select
    coalesce(b.custom_places, '{}'::jsonb),
    coalesce(b.user_links, '{}'::jsonb)
  into current_custom_places, current_user_links
  from public.pass_planner_books b
  where b.id = p_id and b.edit_token = p_edit_token
  for update;

  if not found then return; end if;

  current_place := current_custom_places -> p_place_id;
  if jsonb_typeof(current_place) <> 'object' then return; end if;

  observed_google_place_id := trim(coalesce(current_place ->> 'googlePlaceId', ''));
  observed_google_place_name := nullif(trim(coalesce(current_place ->> 'googlePlaceName', '')), '');
  observed_place_name := nullif(trim(coalesce(current_place ->> 'name', '')), '');
  observed_lodging :=
    lower(coalesce(current_place ->> 'category', '')) = 'hotel'
    or lower(coalesce(current_place ->> 'hotelAffiliateManual', 'false')) = 'true'
    or (
      jsonb_typeof(current_place -> 'googlePlaceTypes') = 'array'
      and (current_place -> 'googlePlaceTypes') ? 'lodging'
    );

  if p_provider = 'Agoda' then
    observed_hotel_id := substring(lower(p_href) from '[?&]hid=([0-9]+)');
  else
    observed_hotel_id := coalesce(
      substring(lower(p_href) from '[?&]hotelid=([0-9]+)'),
      substring(lower(p_href) from 'hotel-detail-([0-9]+)')
    );
  end if;

  observed_latitude_text := coalesce(
    nullif(current_place ->> 'googlePlaceLat', ''),
    nullif(current_place ->> 'lat', '')
  );
  observed_longitude_text := coalesce(
    nullif(current_place ->> 'googlePlaceLng', ''),
    nullif(current_place ->> 'lng', '')
  );
  if observed_latitude_text ~ '^-?[0-9]+([.][0-9]+)?$' then
    observed_latitude := observed_latitude_text::double precision;
  end if;
  if observed_longitude_text ~ '^-?[0-9]+([.][0-9]+)?$' then
    observed_longitude := observed_longitude_text::double precision;
  end if;

  if observed_lodging
    and observed_google_place_id ~ '^[A-Za-z0-9_-]{8,180}$'
    and observed_hotel_id ~ '^[0-9]{3,}$'
    and (observed_latitude is null or observed_latitude between -90 and 90)
    and (observed_longitude is null or observed_longitude between -180 and 180) then
    select case
      when p_provider = 'Agoda' and i.agoda_hotel_id = observed_hotel_id then 'promoted'
      when p_provider = 'Trip' and i.trip_hotel_id = observed_hotel_id then 'promoted'
      when p_provider = 'Agoda' and i.agoda_hotel_id is not null then 'conflict'
      when p_provider = 'Trip' and i.trip_hotel_id is not null then 'conflict'
      else 'pending'
    end
    into observed_status
    from public.planner_hotel_affiliate_identities i
    where i.google_place_id = observed_google_place_id
      and i.verification_status = 'verified';

    observed_status := coalesce(observed_status, 'pending');

    insert into public.planner_hotel_affiliate_candidates (
      google_place_id,
      provider,
      hotel_id,
      href,
      google_place_name,
      place_name,
      latitude,
      longitude,
      source_book_id,
      source_place_id,
      status
    ) values (
      observed_google_place_id,
      p_provider,
      observed_hotel_id,
      p_href,
      observed_google_place_name,
      observed_place_name,
      observed_latitude,
      observed_longitude,
      p_id,
      p_place_id,
      observed_status
    )
    on conflict (google_place_id, provider, hotel_id) do update
    set
      href = excluded.href,
      google_place_name = coalesce(excluded.google_place_name, planner_hotel_affiliate_candidates.google_place_name),
      place_name = coalesce(excluded.place_name, planner_hotel_affiliate_candidates.place_name),
      latitude = coalesce(excluded.latitude, planner_hotel_affiliate_candidates.latitude),
      longitude = coalesce(excluded.longitude, planner_hotel_affiliate_candidates.longitude),
      source_book_id = excluded.source_book_id,
      source_place_id = excluded.source_place_id,
      status = case
        when excluded.status = 'promoted' then 'promoted'
        when planner_hotel_affiliate_candidates.status = 'promoted' then 'promoted'
        when excluded.status = 'conflict' then 'conflict'
        else planner_hotel_affiliate_candidates.status
      end,
      seen_count = planner_hotel_affiliate_candidates.seen_count + 1,
      last_seen_at = now();

    -- Pending/conflicting observations are review material, not permanent
    -- business data. Keep trusted/promoted evidence indefinitely, but bound
    -- every other candidate both by age and by Place/provider cardinality.
    delete from public.planner_hotel_affiliate_candidates c
    where c.status <> 'promoted'
      and c.last_seen_at < now() - interval '180 days';

    delete from public.planner_hotel_affiliate_candidates c
    where c.id in (
      select overflow.id
      from public.planner_hotel_affiliate_candidates overflow
      where overflow.google_place_id = observed_google_place_id
        and overflow.provider = p_provider
        and overflow.status <> 'promoted'
      order by overflow.last_seen_at desc, overflow.id desc
      offset 10
    );
  end if;

  current_place_links := case
    when jsonb_typeof(current_place -> 'links') = 'array' then current_place -> 'links'
    else '[]'::jsonb
  end;

  -- Preserve manual links in user_links and any previously stored provider
  -- link. A later automatic result must never replace either one.
  if exists (
    select 1
    from jsonb_array_elements(current_place_links) item
    where lower(coalesce(item ->> 'label', '')) = lower(p_provider)
      or lower(coalesce(item ->> 'href', '')) ~ ('^https://([a-z0-9-]+\.)*' || provider_domain || '(/|$)')
  ) or exists (
    select 1
    from jsonb_array_elements(case when jsonb_typeof(current_user_links -> p_place_id) = 'array' then current_user_links -> p_place_id else '[]'::jsonb end) item
    where lower(coalesce(item ->> 'label', '')) = lower(p_provider)
      or lower(coalesce(item ->> 'href', '')) ~ ('^https://([a-z0-9-]+\.)*' || provider_domain || '(/|$)')
  ) then
    return query
    select b.id, b.read_token, b.updated_at, false
    from public.pass_planner_books b
    where b.id = p_id and b.edit_token = p_edit_token;
    return;
  end if;

  if jsonb_array_length(current_place_links) >= 8 then
    return query
    select b.id, b.read_token, b.updated_at, false
    from public.pass_planner_books b
    where b.id = p_id and b.edit_token = p_edit_token;
    return;
  end if;

  next_place_links := current_place_links || jsonb_build_array(jsonb_build_object('label', p_provider, 'href', p_href));

  return query
  update public.pass_planner_books b
  set
    custom_places = jsonb_set(
      current_custom_places,
      array[p_place_id],
      jsonb_set(current_place, '{links}', next_place_links, true),
      true
    ),
    expires_at = now() + interval '365 days'
  where b.id = p_id and b.edit_token = p_edit_token
  returning b.id, b.read_token, b.updated_at, true;
end;
$$;

revoke all on function public.planner_book_add_affiliate_link(text, text, text, text, text) from public;
grant execute on function public.planner_book_add_affiliate_link(text, text, text, text, text) to anon, authenticated;

-- Only a service-role/admin operation may turn an observed candidate into a
-- globally reusable identity. Existing conflicting provider IDs are rejected
-- instead of being overwritten silently.
create or replace function public.planner_hotel_affiliate_identity_promote(
  p_google_place_id text,
  p_provider text,
  p_hotel_id text,
  p_verified_by text default 'service_role'
)
returns public.planner_hotel_affiliate_identities
language plpgsql
security definer
set search_path = public
as $$
declare
  candidate public.planner_hotel_affiliate_candidates%rowtype;
  names jsonb;
  promoted public.planner_hotel_affiliate_identities%rowtype;
begin
  if p_provider not in ('Agoda', 'Trip')
    or p_google_place_id !~ '^[A-Za-z0-9_-]{8,180}$'
    or p_hotel_id !~ '^[0-9]{3,}$' then
    raise exception 'invalid hotel affiliate identity';
  end if;

  select c.* into candidate
  from public.planner_hotel_affiliate_candidates c
  where c.google_place_id = p_google_place_id
    and c.provider = p_provider
    and c.hotel_id = p_hotel_id
    and c.status <> 'rejected'
  for update;

  if not found then
    raise exception 'hotel affiliate candidate not found';
  end if;

  if p_provider = 'Agoda' and exists (
    select 1 from public.planner_hotel_affiliate_identities i
    where i.google_place_id = p_google_place_id
      and i.agoda_hotel_id is not null
      and i.agoda_hotel_id <> p_hotel_id
  ) then
    raise exception 'verified Agoda identity conflict';
  end if;
  if p_provider = 'Trip' and exists (
    select 1 from public.planner_hotel_affiliate_identities i
    where i.google_place_id = p_google_place_id
      and i.trip_hotel_id is not null
      and i.trip_hotel_id <> p_hotel_id
  ) then
    raise exception 'verified Trip identity conflict';
  end if;

  select coalesce(jsonb_agg(to_jsonb(n.name)), '[]'::jsonb)
  into names
  from (
    select distinct value as name
    from (values (candidate.google_place_name), (candidate.place_name)) values_list(value)
    where value is not null and trim(value) <> ''
  ) n;

  if p_provider = 'Agoda' then
    insert into public.planner_hotel_affiliate_identities (
      google_place_id, canonical_names, latitude, longitude,
      agoda_hotel_id, agoda_hotel_name, agoda_source_url,
      verified_by, verified_at
    ) values (
      candidate.google_place_id, names, candidate.latitude, candidate.longitude,
      candidate.hotel_id, coalesce(candidate.google_place_name, candidate.place_name), candidate.href,
      left(coalesce(nullif(trim(p_verified_by), ''), 'service_role'), 120), now()
    )
    on conflict (google_place_id) do update set
      canonical_names = case
        when jsonb_array_length(planner_hotel_affiliate_identities.canonical_names) > 0
          then planner_hotel_affiliate_identities.canonical_names
        else excluded.canonical_names
      end,
      latitude = coalesce(excluded.latitude, planner_hotel_affiliate_identities.latitude),
      longitude = coalesce(excluded.longitude, planner_hotel_affiliate_identities.longitude),
      agoda_hotel_id = excluded.agoda_hotel_id,
      agoda_hotel_name = excluded.agoda_hotel_name,
      agoda_source_url = excluded.agoda_source_url,
      verification_status = 'verified',
      verified_by = excluded.verified_by,
      verified_at = excluded.verified_at,
      updated_at = now()
    returning * into promoted;
  else
    insert into public.planner_hotel_affiliate_identities (
      google_place_id, canonical_names, latitude, longitude,
      trip_hotel_id, trip_hotel_name, trip_source_url,
      verified_by, verified_at
    ) values (
      candidate.google_place_id, names, candidate.latitude, candidate.longitude,
      candidate.hotel_id, coalesce(candidate.google_place_name, candidate.place_name), candidate.href,
      left(coalesce(nullif(trim(p_verified_by), ''), 'service_role'), 120), now()
    )
    on conflict (google_place_id) do update set
      canonical_names = case
        when jsonb_array_length(planner_hotel_affiliate_identities.canonical_names) > 0
          then planner_hotel_affiliate_identities.canonical_names
        else excluded.canonical_names
      end,
      latitude = coalesce(excluded.latitude, planner_hotel_affiliate_identities.latitude),
      longitude = coalesce(excluded.longitude, planner_hotel_affiliate_identities.longitude),
      trip_hotel_id = excluded.trip_hotel_id,
      trip_hotel_name = excluded.trip_hotel_name,
      trip_source_url = excluded.trip_source_url,
      verification_status = 'verified',
      verified_by = excluded.verified_by,
      verified_at = excluded.verified_at,
      updated_at = now()
    returning * into promoted;
  end if;

  update public.planner_hotel_affiliate_candidates c
  set status = case when c.hotel_id = p_hotel_id then 'promoted' else 'conflict' end,
      last_seen_at = now()
  where c.google_place_id = p_google_place_id
    and c.provider = p_provider
    and c.status <> 'rejected';

  return promoted;
end;
$$;

revoke all on function public.planner_hotel_affiliate_identity_promote(text, text, text, text) from public, anon, authenticated;
grant execute on function public.planner_hotel_affiliate_identity_promote(text, text, text, text) to service_role;

-- First manually verified identity: R&B Hotel Otsuka-eki Kita-guchi.
insert into public.planner_hotel_affiliate_identities (
  google_place_id,
  canonical_names,
  latitude,
  longitude,
  country_code,
  agoda_hotel_id,
  agoda_hotel_name,
  agoda_source_url,
  trip_hotel_id,
  trip_hotel_name,
  trip_source_url,
  verified_by,
  verified_at
) values (
  'ChIJka6-9XaNGGARXGsXzYnNCPw',
  '["R&B Hotel Otsuka-eki Kita-guchi", "R&B HOTEL 大塚站北口", "華盛頓R&B HOTEL 大塚站北口", "Washington R&B Hotel Otsukaeki-Kitaguchi"]'::jsonb,
  35.7322094,
  139.7292317,
  'JP',
  '255691',
  'Washington R&B Hotel Otsukaeki-Kitaguchi',
  'https://www.agoda.com/partners/partnersearch.aspx?pcs=1&cid=1945734&hid=255691',
  '1005575',
  'Washington R&B Hotel Otsukaeki Kitaguchi',
  'https://tw.trip.com/hotels/tokyo-hotel-detail-1005575/randb-hotel-otsukaeki-kitaguchi?Allianceid=6833709&SID=242535686&trip_sub1=&trip_sub3=D19955455',
  'manual:jiejourneys',
  '2026-09-24T00:00:00Z'::timestamptz
)
on conflict (google_place_id) do update set
  canonical_names = excluded.canonical_names,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  country_code = excluded.country_code,
  agoda_hotel_id = excluded.agoda_hotel_id,
  agoda_hotel_name = excluded.agoda_hotel_name,
  agoda_source_url = excluded.agoda_source_url,
  trip_hotel_id = excluded.trip_hotel_id,
  trip_hotel_name = excluded.trip_hotel_name,
  trip_source_url = excluded.trip_source_url,
  verification_status = 'verified',
  verified_by = excluded.verified_by,
  verified_at = excluded.verified_at,
  updated_at = now();

notify pgrst, 'reload schema';
commit;
